# Generated by Django 3.2.8 on 2022-02-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_userswithlistinginwatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='usersWithListingInWatchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
    ]
