# Generated by Django 3.2.8 on 2022-02-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(default='comment title', max_length=100),
        ),
    ]
